### ISSUE TITLE
  OSX arm64 build? 

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/tig-feedstock#3]
### Comment:

There's no arm build for this feedstock, so it can't be installed on Apple Silicon chips. (`brew` provides an arm build, so one _should_ be feasible, but is beyond me.) Any chance of an arm build?

**Comment by dbast** [comment]
done via https://github.com/conda-forge/tig-feedstock/pull/6 and https://github.com/conda-forge/tig-feedstock/pull/7
